

title: "YODA MOUSSA JUNIOR | Data Analyst"
description: "Portfolio Data Analyst - Power BI, SQL, Python"
lang: fr-FR
theme: minimal-mistakes-jekyll

# Logo / avatar
header:
  logo: img/ym.jpg

# RÃ©seaux sociaux
social:
  github: mozak-dev
  linkedin: yoda-moussa-junior

